language: objective-c
cache:
  directories:
    - Example/vendor/bundle
install:
  - (cd Example && bundle install --path=vendor/bundle --binstubs=vendor/bin && bundle exec pod install)
script:
  - (cd Example && bundle exec rake build test)
after_success:
  - (cd Example && bundle exec rake coverage:coveralls)
branches:
  only:
    - master
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
